const { Router } = require('express');
const router = Router();
const controller = require('../controllers/ensayo_archivados.controllers');
router.get('/', controller.getAll);
router.get('/:idEnsayo', controller.getById);
router.post('/:idEnsayo', controller.restoreEnsayo);
router.delete('/:idEnsayo', controller.delete);
router.get('/:idEnsayo/parametros_archivados', controller.getAllParametros);
router.get('/:idEnsayo/parametros_archivados/:idParametro', controller.getAParametro);
router.get('/:idEnsayo/ambiente', controller.getAllAmbiente);
router.get('/:idEnsayo/ambiente/:idAmbiente', controller.getAnAmbiente);
module.exports = router;