const { Router } = require('express');
const router = Router();
const controller = require('../controllers/ensayo.controllers');
router.get('/', controller.getAll);
router.get('/:idEnsayo', controller.getById);
router.post('/', controller.new);
router.delete('/:idEnsayo', controller.delete);
router.put('/:idEnsayo', controller.change);
router.get('/:idEnsayo/parametros', controller.getAllParametros);
router.get('/:idEnsayo/parametros/:idParametro', controller.getAParametro);
router.get('/:idEnsayo/ambiente', controller.getAllAmbiente);
router.get('/:idEnsayo/ambiente/:idAmbiente', controller.getAnAmbiente);
router.get('/:idEnsayo/probetas', controller.getAllProbeta);
router.get('/:idEnsayo/probetas/:idProbeta', controller.getAProbeta);
module.exports = router;